name       : psensor
version    : 1.2.1
release    : 15
source     :
    - https://wpitchoune.net/psensor/files/psensor-1.2.1.tar.gz : 084f785d169f533d3010e50c5933436ed427afc70d41740b762f1db5034833ab
homepage   : https://wpitchoune.net/psensor/
license    : GPL-2.0-only
component  : system.utils
summary    : Psensor is a graphical hardware temperature monitor for Linux
description: |
    Psensor is a graphical hardware temperature monitor for Linux. It can monitor the temperature of motherboard and CPU sensors, the temperature of the NVidia and ATI GPUs, the temperature of the Hard Disk Drives, the rotation speed of the fans, the temperature of a remote computer and the CPU usage.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-c)
    - pkgconfig(libatasmart)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(udisks2)
    - lm_sensors-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share/doc
