name       : psensor
version    : 1.2.0
release    : 6
source     :
    - http://wpitchoune.net/psensor/files/psensor-1.2.0.tar.gz : 99708b313be2cf2d997aacfb6ab13288384c8c3f76266825093013bf568babea
homepage   : http://wpitchoune.net/blog/psensor/
license    : GPL-2.0
component  : desktop.util
summary    : Psensor is a graphical hardware temperature monitor for Linux
description: |
    A Graphical Temperature Monitor
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-c)
    - pkgconfig(libatasmart)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(udisks2)
    - lm_sensors-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
