name       : psensor
version    : 1.1.5
release    : 4
source     :
    - https://wpitchoune.net/psensor/files/psensor-1.1.5.tar.gz : c5695f8e52094a58387689b7403f5bcc0279b5e97bfa9b954988510e25ffe663
homepage   : http://wpitchoune.net/blog/psensor/
license    : GPL-2.0
component  : desktop.util
summary    : Psensor is a graphical hardware temperature monitor for Linux
description: |
    A Graphical Temperature Monitor
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libatasmart)
    - pkgconfig(json-c)
    - pkgconfig(udisks2)
    - lm_sensors-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
