name        : psensor
version     : 1.1.3
release     : 3
source      :
    - http://wpitchoune.net/psensor/files/psensor-1.1.3.tar.gz : 340239451bf2d6fe7f725c80e7f177220fb59e1ec8dc081d4e84599792f94d0a
homepage    : http://wpitchoune.net/blog/psensor/
license     :
    - GPLv2+
summary     : Psensor is a graphical hardware temperature monitor for Linux
description : |
    A Graphical Temperature Monitor
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libatasmart)
    - pkgconfig(json-c)
    - pkgconfig(udisks2)
    - lm_sensors-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
