name       : psensor
version    : 1.2.1
release    : 12
source     :
    - https://wpitchoune.net/psensor/files/psensor-1.2.1.tar.gz : 084f785d169f533d3010e50c5933436ed427afc70d41740b762f1db5034833ab
homepage   : http://wpitchoune.net/blog/psensor/
license    : GPL-2.0-only
component  : desktop.util
summary    : Psensor is a graphical hardware temperature monitor for Linux
description: |
    A Graphical Temperature Monitor
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-c)
    - pkgconfig(libatasmart)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(udisks2)
    - lm_sensors-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
